### ISSUE TITLE
Github action is failing

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-web#34]
Github action is failing during pnpm setup

**Comment by clementinelove** [comment]
Looks like action-setup script is out of date.

I am not familiar with GitHub actions though, will update this line to newer versions do the job?

https://github.com/now-u/now-u-web/blob/1d784dad0e86b45c58b9d371b872b1bc7abd0ce0/.github/workflows/lint.yaml#L15

replace the old version with

```yaml                
uses: pnpm/action-setup@v4.0.0
```
