### ISSUE TITLE
Replace `openapi-typescript-fetch` with `openapi-fetch` 

### ISSUE THREAD

**Issue by clementinelove** [now-u/now-u-web#44]
I just encountered some weird typing problem with `openapi-typescript-fetch` (See image). Basically to solve this problem it looks like we need to feed extra typing info to the fetcher client, which is not documented anywhere except [this issue on GitHub](https://github.com/ajaishankar/openapi-typescript-fetch/issues/28). 
<img width="809" alt="Screenshot 2024-09-02 at 22 57 32" src="https://github.com/user-attachments/assets/57b6032c-6807-48ed-af28-4ee099c51be1">

Considering we’ve previously encountered the es-lint typing issue with this library plus the fact that this repo is not being actively maintained, I think it’s safe for us to move from `openapi-typescript-fetch` to [`openapi-fetch`](https://github.com/openapi-ts/openapi-typescript/tree/main/packages/openapi-fetch) , which is made by the same team behind `openapi-typescript`, no manual typing + better documentation + actively maintained. It's still a wrapper of fetch API so it should work just fine.

What do you think @JElgar ? If that's okay I can create a pull request to replace current use of `openapi-typescript-fetch` with `openapi-fetch`. Should be easy.

**Comment by JElgar** [comment]
Yeah sounds very sensible! Go for it 🚀
