### ISSUE TITLE
Add partnership info page

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-web#49]
https://www.figma.com/design/Z1Ol2UJNsUbdCc2lrCUoWF/WEBSITE-MASTER?node-id=44-262&node-type=frame&t=1jPvVtr1lTIh4WH2-0

**Comment by YWKlai** [comment]
- [Partnership brief doc](https://docs.google.com/document/d/1EX9VHtpoX5KbRTffs5GV5drv70t1oIei/edit#heading=h.sv7xkgqj8ksr)
- [Partnership figma](https://www.figma.com/design/Z1Ol2UJNsUbdCc2lrCUoWF/WEBSITE-MASTER?node-id=44-262&node-type=frame&t=1jPvVtr1lTIh4WH2-0)
- Page name: Charity Partnerships
- Slug: charity-partnership/
- URL: https://www.now-u.com/charity-partnership/
- Partner with us CTA link: https://forms.monday.com/forms/cc4aaf4815a82d3f5450e5f519a12f1f?r=euc1
